name: ✨ Feature Request / 功能建议
description: Suggest an idea or improvement / 提出功能建议
title: "feat: "
labels:
  - "enhancement"

body:

  - type: textarea
    id: description
    attributes:
      label: Description / 功能描述
      description: |
        Describe your idea.
        描述你的需求。
    validations:
      required: true


  - type: textarea
    id: use_case
    attributes:
      label: Use case / 使用场景
      description: |
        Why is this useful?
        为什么需要这个功能？


  - type: textarea
    id: additional
    attributes:
      label: Additional information / 补充信息
      description: |
        Add screenshots or examples if available.
        如有截图或示例，请提供。
